[global_tags]

[agent]
  interval = "60s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = "BuzzVerse"
  omit_hostname = false

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "gwTFtAnBRUM3OYmwsZ0GTg2C6r63bZ1G"
  organization = "BuzzVerse"
  bucket = "lora_db"

  [[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  username = "admin"
  password = "zaq1@WSX"
  topics = [
    "sensors/+/data",
  ]
  topic_tag = "device_id"
  data_format = "json_v2"

  [[inputs.mqtt_consumer.topic_parsing]]
    topic = "sensors/+/data"
    measurement = "sensor_data"
    tags = "_/device_id/_"

  [[inputs.mqtt_consumer.json_v2]]
    measurement_name = "sensor_data"
    
    # BME280 sensor
    [[inputs.mqtt_consumer.json_v2.object]]
      path = "BME280"
      optional = true
      tags = ["BME280"]
      [inputs.mqtt_consumer.json_v2.object.fields]
        temperature = "float"
        humidity = "float"
        pressure = "float"

    # GPS sensor
    [[inputs.mqtt_consumer.json_v2.object]]
      path = "GPS"
      optional = true
      tags = ["GPS", "HEATMAP"]
      [inputs.mqtt_consumer.json_v2.object.fields]
        status = "int"
        altitude = "float"
        latitude = "float"
        longitude = "float"

    # BMA400 sensor
    [[inputs.mqtt_consumer.json_v2.object]]
      path = "BMA400"
      optional = true
      tags = ["BMA400"]
      [inputs.mqtt_consumer.json_v2.object.fields]
        x = "float"
        y = "float"
        z = "float"

    # MQ2 sensor
    [[inputs.mqtt_consumer.json_v2.object]]
      path = "MQ2"
      optional = true
      tags = ["MQ2"]
      [inputs.mqtt_consumer.json_v2.object.fields]
        gas_type = "int"
        value = "float"

    # META
    [[inputs.mqtt_consumer.json_v2.object]]
      path = "META"
      optional = true
      tags = ["META"]
      [inputs.mqtt_consumer.json_v2.object.fields]
        rssi = "float"
        snr = "float"